### ISSUE TITLE
Saving BioCircos Output

### ISSUE THREAD

**Issue by travis-m-blimkie** [lvulliard/BioCircos.R#1]
Hello, 
I am using the BioCircos R package, and was wondering if it is possible to save the output of `BioCircos()` in another format apart from html? Specifically, I was hoping to save the output as an SVG image so I could further tweak it in Inkscape.
Thanks!

**Comment by nickjhathaway** [comment]
So you can accomplish this by making the plot in an RMarkdown document and adding some javascript to add a button to download the SVG of the plot, here is a gist of an example I've made. Basically, you use the `elementId=` argument in the `BioCircos()` command to give your plot an ID and then you grab the svg element within it and download it while adding atrributes so Inkcsape will like it. This actually works for any SVG element as long as there isn't external CSS that modifies the svg elements as this won't be donwloaded. 

https://gist.github.com/nickjhathaway/49f7c930749cf5ebdc486de91b5ee10e

**Comment by travis-m-blimkie** [comment]
Got it working, thanks for the reply!
