### ISSUE TITLE
Saving interactive HTML file

### ISSUE THREAD

**Issue by kalebgatto** [lvulliard/BioCircos.R#21]
Dear developer and colleagues
I am trying to design a circos plot using BioCircos R package. I read the documentation that BioCircos allows to save the plots as .html interactive files. However, when I run the package using RScript the saved .html file is empty. To save the .html file I used saveWidget option from htmlwidgets package. Is it something wrong with saveWidget option? The code I used follows:
```
#!/usr/bin/Rscript
######R script for BioCircos test
library(htmlwidgets)
library(BioCircos)
Chra_Chrb_genomes <- list("Chra1" = 217471166, "Chra2" = 181034961, "Chra3" = 153873357, "Chra4" = 153961319, "Chra5" = 164033575,
    "Chra6" = 154486312, "Chra7" = 133565930, "Chra8" = 147241510, "Chra9" = 91218944, "Chra10" = 52432566, "Chrb1" = 843366180, "Chrb2" = 842558404, "Chrb3" = 707956555, "Chrb4" = 635713434, "Chrb5" = 567300182,
    "Chrb6" = 439630435, "Chrb7" = 236595445, "Chrb8" = 231667822, "Chrb9" = 230778867, "Chrb10" = 151572763, "Chrb11" = 103205957) # custom genome
links_chromosomes_01 <- c("Chra1", "Chra2", "Chra3", "Chra4", "Chra4", "Chra5", "Chra6", "Chra7", "Chra7", "Chra8", "Chra8", "Chra9", "Chra10") # Chromosomes on which the links should start
links_chromosomes_02 <- c("Chrb2", "Chrb3", "Chrb1", "Chrb9", "Chrb10", "Chrb4", "Chrb5", "Chrb6", "Chrb1", "Chrb8", "Chrb3", "Chrb7", "Chrb6") # Chromosomes on which the links should end
links_pos_01 <- c(115060347, 102611974, 14761160, 128700431, 128681496, 42116205, 58890582, 40356090, 146935315, 136481944, 157464876, 39323393, 84752508, 136164354, 99573657, 102580613, 111139346, 120764772, 90748238, 122164776, 44933176, 18823342, 48771409, 128288229, 150613881, 18509106, 123913217, 51237349, 34237851, 53357604, 78270031, 25306417, 25320614, 94266153, 41447919, 28810876, 2802465, 45583472, 81968637, 27858237, 17263637, 30569409) ### links Chra chromosomes
links_pos_02 <- c(410543481, 463189512, 825903588, 353914638, 354135472, 717707494, 643107332, 724899652, 583713545, 558756961, 642015290, 154999098, 340216235, 557731577, 643350872, 655077847, 85356666, 157889318, 226411560, 161566470, 109857786, 25338955, 473876792, 124495704, 46258030, 572314729, 141584107, 426419779, 531245660, 220131772, 353941099, 62422773, 62387030, 116923325, 76544045, 33452274, 7942164, 642047816, 215981114, 39278129, 23302654, 418922633) ### links Chrb chromosomes
links_labels <- c("aldh1a3", "amh", "cyp26b1", "dmrt1", "dmrt3", "fgf20", "hhip", "srd5a3",
  "amhr2", "dhh", "fgf9", "nr0b1", "rspo1", "wnt1",
  "aldh1a2", "cyp19a1",
  "lhx9", "pdgfb", "ptch2", "sox10",
  "cbln1", "wt1",
  "esr1", "foxl2", "gata4", "lrpprc", "serpine2", "srd5a2",
  "asns", "ctnnb1", "srd5a1",
  "cyp26a1", "cyp26c1",
  "wnt4",
  "ar", "nr5a1", "ptgds",
  "fgf16",
  "cxcr4", "pdgfa", "sox8",
  "sox9")
tracklist <- BioCircosLinkTrack('myLinkTrack', links_chromosomes_01, links_pos_01,
  links_pos_01, links_chromosomes_02, links_pos_02, links_pos_02,
  maxRadius = 0.55, labels = links_labels)
#plotting results
plot_Chra_Chrb <- BioCircos(tracklist, genome = Chra_Chrb_genomes, genomeFillColor = "RdBu", chrPad = 0.02, displayGenomeBorder = FALSE, genomeLabelTextSize = "10pt", genomeTicksScale = 4e+3,
  elementId = "Chra_Chrb_comp_plot_test.html")
saveWidget(plot_Chra_Chrb, "Chra_Chrb_comp_plot_test.html", selfcontained = F)
```

The command line to run this script:
`Rscript /path_to/Circle_plot_test.r`

I tried to use this script in RStudio (without saveWidget() command), however it took too long to run in my personnel computer and the results was not displayed. However, this could be due to memory usage setup because when I took off some data, the script easily generates the plot in RStudio and I am able to save it. Is there other way to save the .hmtl interactive files using `Rscript` or `R CMD Batch` or am I doing something wrong using htmlwidgets package in my script?
Sorry if it is a basic question. 
Thanks all in advance for any help and comments.
Sincerely
Kaleb Gatto

**Comment by koalive** [comment]
Hi there! 
The `saveWidget` is usually a good method to save your BioCircos plot. I can confirm that your example leads to an empty html file for me as well, whereas the following example generates the expected output:
```
library(htmlwidgets)
library(BioCircos)
pbc = BioCircos(yChr = FALSE, chrPad = 0, genomeFillColor = "Blues")
saveWidget(pbc, "pbc.html")
```
Maybe try simplifying your plot and see what works. For instance by changing the definition of `plot_Chra_Chrb`  as follows, the file displays the Link track properly:
`plot_Chra_Chrb <- BioCircos(tracklist, genome = Chra_Chrb_genomes, genomeFillColor = "RdBu", chrPad = 0.02, displayGenomeBorder = FALSE)`
Cheers.

**Comment by kalebgatto** [comment]
Hi Dr. Vulliard
I made the changes in ```plot_Chra_Chrb``` as you advised and it worked perfectly.
Thank you for the help
Best Regards
Kaleb
