### ISSUE TITLE
Figures not showing in Rstudio's viewer pane

### ISSUE THREAD

**Issue by koalive** [lvulliard/BioCircos.R#3]
> Dear Sir,
> 
> 
> My name is X. I'm a postdoctoral fellow. I was trying to use Biocircos using Rstudio for my publication following the vignette instructions. I'm having a problem with the package to degenerate the plot in R studio.
> 
> > library(BioCircos)
> > BioCircos()
> > BioCircos(genome = "hg19", yChr = FALSE, genomeFillColor = "Reds", chrPad = 0, displayGenomeBorder = FALSE, genomeTicksDisplay = FALSE, genomeLabelDy = 0)
> 
> Can you please tell me if I am doing something wrong?
> 
> Thanks a lot for your help.
> 
> 
> Best regards,

> The problem is that nothing is showing up. In the Rstudio plot viewer tehre's nothing. There's no error message. I'm using R version 3.4.3 and rstudio-xenial-1.1.442-amd64.
> 
> Please can you fix it.
> 
> Thanks a lot.
> 
> Best regards,

Dear X,

It seems to be a problem coming from Rstudio's viewer pane, probably because it runs an old version of JavaScript. I am unsure of how to solve that for now and don't have much time for that right now, but one possible workaround is to display it in your browser instead of Rstudio's viewer.

You can either use R outside of Rstudio or after having entered your commands in Rstudio, export the figure to an HTML file and open it in your browser (and it will still be interactive). See the screenshot enclosed for the location of this option in Rstudio.

I will let you know if I find a better solution.

Best regards,

Loan

![biocircosrstudiobug](https://user-images.githubusercontent.com/6972580/52863076-24179b80-3137-11e9-807c-bb7f1577da3c.png)

**Comment by Mohsin0911** [comment]
hi, i also found  same problem
